# Bun configuration file

[install]
# Respect peer dependencies
peer = true

# Use exact versions like npm
exact = false

# Install dev dependencies
dev = true

[test]
# Root directory for tests
root = "./tests"

# Coverage settings
coverage = true
coverageReporter = ["text", "lcov"]
coverageThreshold = { line = 75, function = 80, branch = 60, statement = 75 }

# Test timeout (in ms)
timeout = 10000

# Preload files before running tests
preload = ["./tests/setup.bun.ts"]

[run]
# Auto-install missing packages
install = true

# Use .env files
dotenv = true