name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        bun-version: [1.1.35, latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun ${{ matrix.bun-version }}
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Run type checking
        run: bun run typecheck

      - name: Build project
        run: bun run build

      - name: Run tests with coverage
        run: bun run test:coverage

      - name: Upload coverage to Codecov
        if: matrix.bun-version == '1.1.35'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: false

  # Separate job for checking coverage thresholds
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.35'

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Check coverage thresholds
        run: bun run test:coverage -- --coverage --coverageThreshold='{"global":{"lines":75,"functions":80,"branches":60,"statements":75}}'