name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.35'

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Run tests
        run: bun test

      - name: Package release artifacts
        run: |
          # Create release directory
          mkdir -p release
          
          # Copy built files
          cp -r dist release/
          cp -r config release/
          cp package.json release/
          cp bun.lockb release/ || echo "bun.lockb not found"
          cp docs/README.md release/README.md || echo "README.md not found"
          cp LICENSE release/ || echo "LICENSE not found"
          cp CLAUDE.md release/
          
          # Create tarball
          tar -czf cui-server-${{ github.ref_name }}.tar.gz -C release .
          
          # Create zip
          cd release && zip -r ../cui-server-${{ github.ref_name }}.zip . && cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cui-server-${{ github.ref_name }}.tar.gz
            cui-server-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-npm:
    needs: release
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: '1.1.35'

      - name: Setup Node.js for npm publish
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: bun install

      - name: Build project
        run: bun run build

      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}